### ISSUE TITLE
Создать гугл-опрос для бизнес-анализа

### ISSUE THREAD

**Issue by SabinaAlieva** [unit-team-spbu/aggregator#2]
# Задача

Требуется сделать Google форму для пользователей на основе обсуждения от #1. Вопросы в [wiki](https://github.com/unit-team-spbu/aggregator/wiki/%D0%9E%D0%BF%D1%80%D0%BE%D1%81-%D0%B4%D0%BB%D1%8F-%D0%91%D0%B8%D0%B7%D0%BD%D0%B5%D1%81-%D0%90%D0%BD%D0%B0%D0%BB%D0%B8%D0%B7%D0%B0)

Ссылку на форму скинуть сюда, дальнейшее обсуждение здесь

**Comment by Blinova-Olga** [comment]
Оставляю ссылку на сделанный опрос

**Comment by Blinova-Olga** [comment]
https://docs.google.com/forms/d/1Jp4rzqVOShL0y3MdGjJnNzoVL8eSXMFTY95lv7EgzyQ/edit?usp=sharing
