### ISSUE TITLE
Сделать макеты всех страниц сайта

### ISSUE THREAD

**Issue by SabinaAlieva** [unit-team-spbu/aggregator#3]
Для макетов можно использовать [Figma](https://www.figma.com/). Ссылку на макет в комментарий, обсуждение в Figma (нужно проверить бесплатность этой фичи, но она там была)

- [x] Страница со списком событий, фильтром событий, поисковой строкой, баннером для рекламы, кнопкой лк, вход\выход\регистрация

- [x] Страница регистрации с анкетой о предпочтениях

- [x] Личный кабинет, с возможностью изменения личной инфы, изменением ответов анкеты о предпочтениях

---

To-do по отзывам Влада

- [ ] сделать макеты для различных устройств
   - [ ] компьютеры (выбрать какое-нибудь наиболее распространенное соотношение сторон типа 16:9/16:10 и сделать макет каждой страницы под него)
   - [ ] мобильные устройства (-//-)

> в Figma есть шаблоны для различных разрешений экрана и устройств, так что можно просто воспользоваться ими

- [ ] заполнить контент страниц какими-нибудь моками

**Дополнительно**

- [ ] т.к. стоит задача сделать адаптивную верстку, то рекомендуется изучить css grid и flexbox

После выполнения работ, ссылку на результат скинуть в комментарии, желательно приложить ссылку к исходникам, обсудить результат c @Blinova-Olga и @SabinaAlieva

**Comment by IrinaS-77** [comment]
https://drive.google.com/folderview?id=1cNX1PXVkKGsZ2w7uRl2fYSz68LaPnY2q

**Comment by IrinaS-77** [comment]
[Вход.pdf](https://github.com/unit-team-spbu/aggregator/files/5356225/default.pdf)
[Uploading Регистрация.pdf…]()

[Uploading Событие.pdf…]()

**Comment by IrinaS-77** [comment]
[Uploading Вход.pdf…]()

**Comment by katunilya** [comment]
@IrinaS-77 фиксирую отзывы Влада:

Интерфейс слишком крупный и более ориентирован на планшеты или устройства с маленьким экраном, на устройствах с большим экраном будет смотреться странно.

Новые to-do поместил в главное сообщение issue, там же доп. комментарии.
