### ISSUE TITLE
Составить UML диаграммы пользовательских сценариев

### ISSUE THREAD

**Issue by SabinaAlieva** [unit-team-spbu/aggregator#5]
Как варинта можно использовать нотацию Use-case UML Diagrams (см. [видео](https://www.youtube.com/watch?v=zid-MVo7M-E&t=1s) или [Specififcation by Example](https://habr.com/ru/post/166747/) (In Order To - As A - I Want)).

Результат в wiki на отдельной странице; ссылку на ревью сюда

**Comment by Blinova-Olga** [comment]
https://github.com/unit-team-spbu/aggregator.wiki.git

**Comment by Blinova-Olga** [comment]
UML диаграммы пользовательских сценариев

Ссылка на картинку https://drive.google.com/file/d/1tioIlrJUTE8Gv8XijI5GVdxllS7SVxg_/view?usp=sharing

Ссылка на документ. https://drive.google.com/file/d/1_5HDVm9Bit8OOoJnFrgnIRmS0uer-qff/view?usp=sharing

Открывать через https://app.diagrams.net/
