### ISSUE TITLE
Поиск и анализ существующих решений и источников

### ISSUE THREAD

**Issue by SabinaAlieva** [unit-team-spbu/aggregator#7]
Найти еще решения, которые могут быть нам акутальны:

- [x] группы вконтакте

- [ ] телеграм каналы

- [x] прочие сайты

- [x] Сделать таблицу или список, в котором 
   * описан источник, 
   * что там есть, 
   * плюсы, минусы, 
   * насколько популярен, 
   * чем интересен нам, насколько много в нем информации

Результат скинуть в виде ссылки сюда в комментарии
Отписаться в лс

**Comment by Blinova-Olga** [comment]
Прикрепляю ссылку на документ https://drive.google.com/file/d/1oPdf175Mhl241YaVXk_f6uY3bhDz1W4d/view?usp=sharing

**Comment by SabinaAlieva** [comment]
После обсуждения решили, что пока телеграм каналы использовать все равно не будем и можно их не анализировать
