### ISSUE TITLE
Составить Business Canvas или Lean Canvas

### ISSUE THREAD

**Issue by SabinaAlieva** [unit-team-spbu/aggregator#8]
* [Пример Lean Canvas](https://leadstartup.ru/db/lean-canvas)
* [Пример Business Canvas](https://vc.ru/flood/105386-biznes-model-kanvas-opisanie-modeli-i-ee-primery)

Ссылку на схему кинуть в комментарии

**Comment by Blinova-Olga** [comment]
Lean Canvas 
прикрепляю ссылку на документ https://drive.google.com/file/d/1-3fYChtj05vjrtwCOWbj0FVc5sideqI4/view?usp=sharing
ссылка на картинку https://drive.google.com/file/d/16rn_5WFgla3y2OMnRPW6tDizQYVKERsy/view?usp=sharing
